<a href="https://colab.research.google.com/github/maryadriennerdrgz/CpE-AIML/blob/main/58033_LAB2_LakadMatatag.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [8]:
class LRegression():
  def __init__(self, dataFrame, y_GndTruth, thetaVector):
    self.dataFrame = dataFrame
    self.y_GndTruth = y_GndTruth
    self.thetaVector = thetaVector

  def getVectorMagnitude(self):
    magnitude - np.linalg.norm(self.thetaVector)
    return magnitude

  def getZ(self):  ## Eq. 3.1
    self.z = np.dot(self.dataFrame, self.thetaVector)
    return self.z
  
  def getActivation (self): ## Eq 3.2 and Eq. 3.3
    self.activation = 1/(1+np.exp(self.z))
    return self.activation
  
  def getLoss(self):  ## Eq. 3.4
    m = self.y_GndTruth.shape[0]
    yt = self.y_GndTruth.transpose()

    lossEq = (-1*yt) * (np.log(self.activation)) - ((1-self.y_GndTruth).transpose()) * (np.log(1-self.activation))
    self.j = (1/m) *lossEq
    return self.j


In [17]:
X = np.array ([[0, 1, 0],
              [1, 0, 1],
              [0, -1, 0],
    
])
m = X.shape[1]
theta = np.random.normal(0,1, size = (m, 1))
y = np.random.randint(0,2, size = (m,1))
Regression = LRegression(X, y, theta)

In [18]:
Regression = LRegression(X, y, theta)

In [19]:
Regression.getVectorMagnitude

<bound method LRegression.getVectorMagnitude of <__main__.LRegression object at 0x7f3961aeabd0>>

In [20]:
Regression.getZ()

array([[-0.32803489],
       [ 0.05497821],
       [ 0.32803489]])

In [21]:
Regression.getActivation()

array([[0.58128116],
       [0.48625891],
       [0.41871884]])

In [22]:
Regression.getLoss()

array([[0.18084024, 0.2901852 , 0.2901852 ],
       [0.24033802, 0.22201195, 0.22201195],
       [0.2901852 , 0.18084024, 0.18084024]])